### ISSUE TITLE
How to get full viewport with AR pass-through 

### ISSUE THREAD

**Issue by dorcatty** [stereolabs/zed-unity#157]
Dear all, 

I am testing Zed M camera with Unity3D and Oculus Quest with Oculus Quest Integration. 
I can have the dual view from Zed Camera and AR content via Oculus Link Cable.
However, the viewport has some 'Black cropped' area, such as:

https://gfycat.com/deafeningornerykawala

do we have some solution to view AR Pass-through without black area ? 

thx

**Comment by obraun-sl** [comment]
Hi,
It's not really possible since the FoV of the ZED-M and the Fov of the Quest are not the same (Quest is bigger). 
There is potentially a hack by changing the distance of the rendering plane, but that's not really recommended since images will look distorded.
You can change the parameter here : 
https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/MR/ZEDMixedRealityPlugin.cs#L431
Increase the value (default = 1.0f) or even increase the scaleFromZED value.

**Comment by dorcatty** [comment]
thanks a lot your quick response.
do we have any camera like Zed Mini gives a larger FOV ?
or have you tested with other VR headset ?which goggle has the similar FOV
as Zed Mini ?

Thanks a lot

**Comment by crud89** [comment]
To a certain extent, you can influence the FoV within the HMD by setting [`XRDevice.fovZoomFactor`](https://docs.unity3d.com/ScriptReference/XR.XRDevice-fovZoomFactor.html). However, similar to "stretching" the view plane to match the vision, this also changes the proportions of the user vision, so objects appear larger than they actually are.
