### ISSUE TITLE
ZEDMixedRealityPlugin zed2eye_distance does not match hmdtozedCalibration 

### ISSUE THREAD

**Issue by dogod621** [stereolabs/zed-unity#43]
Hi,

ZEDMixedRealityPlugin  line 376:
It directly use 10 cm as zed2eye_distance ,
but default hmdtozedCalibration is 11.5 cm,
and if I calibrate hmdtozedCalibration via changing ZED-HMD offset calibration file (auto update hmdtozedCalibration ).
zed2eye_distance  will not match at all.

``` C#
void ZEDReady()
	{
		Vector2 scaleFromZED;
		halfBaselineOffset.x = zedCamera.Baseline / 2.0f;

		float perception_distance = 1.0f;
		float zed2eye_distance = 0.1f; //Estimating 10cm between your eye and physical location of the ZED Mini. 
		hasVRDevice = UnityEngine.XR.XRDevice.isPresent;

		if (hasVRDevice) {
			sl.CalibrationParameters parameters = zedCamera.CalibrationParametersRectified;

			scaleFromZED = ComputeSizePlaneWithGamma (new sl.Resolution ((uint)zedCamera.ImageWidth, (uint)zedCamera.ImageHeight),
				perception_distance, zed2eye_distance, offset.z,
				ComputeFocal (new sl.Resolution ((uint)UnityEngine.XR.XRSettings.eyeTextureWidth, (uint)UnityEngine.XR.XRSettings.eyeTextureHeight)),
				parameters.leftCam.fx);
            
			scale (quadLeft.gameObject, scaleFromZED);
			scale (quadRight.gameObject, scaleFromZED);
			ready = false;

		}


```

**Another issue:**
ZEDMixedRealityPlugin  line 641:
```
hmdtozedCalibration.translation.x = 0.0315f;//-zedCamera.Baseline/2;
```
It is -0.0315f, not 0.0315f, although it will be update latter, so it will not cause any error...
But it is still a mistake... 

PS. 
**Another question:**
Why default hmdtozedCalibration do not compute from dllz_get_calibration_parameters (-zedCamera.Baseline/2)... 
But directly write in code. (-zedCamera.Baseline/2 is been comment out)
Although it is match for ZED MINI.

ZEDMixedRealityPlugin  line 636:
```
public void LoadHmdToZEDCalibration()
	{
		if (hasVRDevice) {
			/// Default calibration (may be changed)
			hmdtozedCalibration.rotation = Quaternion.identity;
			hmdtozedCalibration.translation.x = 0.0315f;//-zedCamera.Baseline/2;
			hmdtozedCalibration.translation.y = 0.0f;
			hmdtozedCalibration.translation.z = 0.11f;
```

ZEDMixedRealityPlugin  line 714:
```
private void CreateDefaultCalibrationFile(string path)
	{
		//Default Calibration: DO NOT CHANGE.
		hmdtozedCalibration.rotation = Quaternion.identity;
		hmdtozedCalibration.translation.x = -0.0315f;
		hmdtozedCalibration.translation.y = 0.0f;
		hmdtozedCalibration.translation.z = 0.115f;

```

**Comment by obraun-sl** [comment]
Hi,
zed2eye_distance  and hmdtozedCalibration does not refer to the same distance : 

- zed2eye_distance  is the distance on the Z axis between your eyes and the eyes of the camera. Since the ZED is placed in front of the headset, the images taken from the camera are the same as if they were taken from the eact position of your eyes : this creates a kind of distortion of the 3D space that is compensated by the calculation made just after (using zed2eye_distance  / perception_distance  / camera parameters). The average distance is 10cm and this number should not be changed.

- hmdtozedCalibration refers to distance between the ZED and the HMD tracking frame reference. The tracking frame reference of the ZED is the left sensor of the camera. On the HMD, it's more on the center of the head ( it's not on your eyes, it's more on the head's center). This is used to combine and fuse the positionnal tracking of the ZED and the positionnal tracking of the HMD. 

Note : 
* Indeed it could be : hmdtozedCalibration.translation.x = -zedCamera.Baseline/2; because the ZED should always be placed properly (using the guidelines provided) so that the camera is at the center of the headset (in X axis).
* hmdtozedCalibration.translation.z could be increased to 0.13f; as it's more closed to reality.
