### ISSUE TITLE
spatial mapping and .area file is not exist

### ISSUE THREAD

**Issue by 478161648** [stereolabs/zed-unity#48]
when I stop the spatial mapping,there is only a ZEDMesh.obj, the .area file is not exist.
is someone know this problem? and what should i do ,if i want use the .area file.

**Comment by Abrahamh08** [comment]
Same problem for me. They used to generate, now they don't. No idea why.

**Comment by ckorris** [comment]
Hi all, I came across this recently. The issue is that spatial memory needs to be enabled in ZEDManager in order for it to be recorded. But at some point one of us must've unchecked spatial memory (or updated the prefab) and it got left that way when we uploaded it. Sorry about that. 

For now, just go to the ZEDManager's Inspector in ZED_Rig_Stereo and enable Spatial Memory. That should fix it, and we'll make it default to enabled in the next update.

**Comment by 478161648** [comment]
The stereolab's answer:

Chris (Stereolabs)
Mar 1, 09:28 PST
Hello, I was able to reproduce your issue immediately. The problem is that the ZEDManager component in ZED_Rig_Stereo does not have Spatial Memory enabled. You can enable it in its Inspector. You should then have an .area file after you scan. I will fix this for our next patch, as it should be enabled by default. My apologies. 

Chris
Stereolabs Support
--

**Comment by ckorris** [comment]
^ That's me, and that's how I found out about the issue. Thanks for reporting it and sorry I missed that you also posted on GitHub.
