### ISSUE TITLE
GameObject Drifting in AR

### ISSUE THREAD

**Issue by hankhhub** [stereolabs/zed-unity#69]
I am running ZED-M on Oculus Rift with AR pass-through. In ZED Manager, I have enable tracking and enable spatial memory on. From time to time, when I instantiate my gameobjects on the scene, they drift randomly and couldn't recover back to initial position where it was instantiated. Is there anyway to fix this issue?

**Comment by ckorris** [comment]
The very simplest way to mitigate this would be to uncheck Enable Tracking and rely on your Rift's tracking instead, via base stations. A good outside-in tracking system is almost always more reliable than an inside-out tracking system like we have on the ZED, since you are guaranteed to have a constant, fixed reference point. 

If that's not an option (such if you're not using the base stations) I'd look at your environment and see if there's anything that would make it difficult for the ZED's tracking system to run. An ideal environment has lots of well-textured surfaces, is well lit, and has a minimum of shiny or reflective surfaces. A common scenario that is difficult for the ZED's tracking is a room filled with plain white walls. Also, if there is a lot of movement in front of you, that can sometimes cause drift if the moving objects are much better textured than the background.
