### ISSUE TITLE
[Bug] DontDestroyOnLoad on StereoRig stops mirroring the vr view to screen, when loading a scene

### ISSUE THREAD

**Issue by DrFritzi** [stereolabs/zed-unity#80]
Hi,
loading a new scene with the ZED_Rig_Stereo Prefab set to DontDestroyOnLoad causes the screen to no longer show a mirror of the VR view. 
The screen view just freezes with the last image.

This was tested on Unity 2018.4.2f1, 2019.2.1f1 with the Unity-ZED-SDK v2.8.1 and ZED-SDK v2.8.3

To reproduce this bug, add the ZED_Rig_Stereo to a new scene, and remove the existing camera. On the ZED Manager, set "Don't Destroy on Load" to true.
Add a script that reloads the scene (or loads another scene). E.g.:
``` C#
void Update()
{
     if(Input.GetKeyDown(KeyCode.Space))
     {
         SceneManager.LoadScene(SceneManager.GetActiveScene().name);
         //SceneManager.LoadScene("New Scene");
     }
}
```
After reloading the scene, the VR view will still work, but the GameView is frozen.

Is there a quick fix to solve this problem?

**Comment by ckorris** [comment]
I could replicate immediately, and thankfully the solution is very easy. 

Look for this line in ZEDManager.cs ([line 2073](https://github.com/stereolabs/zed-unity/blob/master/ZEDCamera/Assets/ZED/SDK/Helpers/Scripts/ZEDManager.cs#L2073) as of writing): 

`mirrorContainer = new GameObject("Mirror");`

Somewhere below that, add the following: 

`mirrorContainer.transform.SetParent(transform);`

That will solve it. 

The issue is that we create a separate object to capture the final image for the Game window, but as it's not normally part of the ZED rig, it doesn't inherit the DontDestroyOnLoad setting. You can see this if you comment out the line under the one I linked, where we set mirrorContainer.hideFlags. This corrects that. 

I'll put this in our dev build and it'll be added permanently to the plugin in the next version. Thanks for reporting!
