### ISSUE TITLE
[Feature Request] Depth of field post processing effect.

### ISSUE THREAD

**Issue by cosmic1** [stereolabs/zed-unity#82]
I looked through some of the code in the ZED shaders and they seemed to be designed to support post processing in Unity. To confirm this I tested with color shifting and bloom effects and am able to see the results int he AR pass through. However when I test with depth of field it seems these post processing effects are actually applying to the output eye view quads. Obviously this is fine for some effects but will break down for others like motion blur or depth of field. Is there some way built into the ZED package to achieve a depth of blur effect or will I have to find a way to manually extend the shaders to support this kind of feature?

**Comment by ckorris** [comment]
I poked through the post-processing stack, and it appears this happens because the depth of field shader uses a depth pre-pass (`_CameraDepthTexture`) meaning it's calculated with very simple shaders before the rest of the scene renders. That's an issue because, as you might've seen in our shader, we're updating the depth of the quad on a per-pixel basis in our own shader - but that's going to the depth buffer, not that prepass texture, so it's effectively ignored. 

We don't currently have any features in place for dealing with this, and I would honestly need to do more research into how the effect works to recommend a solution. But some ideas come to mind: 

- Modify DepthOfField.hlsl in the Unity post-processing stack to sample from a custom rendertexture instead of _CameraDepthTexture, and render depth to it after all your important objects have been rendered but before post-processing runs
- Try copying the depth from the ZED shader into _CameraDepthTexture somehow. My feeling is this is hard or impossible but I haven't explored it
- Copy the same functionality of that DepthOfField shader into the ZED shaders, as you said. Though I suggest copying it very closely as you want the effect to match very well - otherwise you'll have a visual separation between the real and virtual worlds

I mentioned those suggestions in the order I did because it's generally better to get the ZED shader to play by the rules of the rest of Unity than to re-implement features it's already running - not just for how much work you have to do, but for assuring that the real and virtual images match as much as possible.
