### ISSUE TITLE
About Motion Accuracy

### ISSUE THREAD

**Issue by 478161648** [stereolabs/zed-unity#91]
![image](https://user-images.githubusercontent.com/37832931/68726863-bfbe3580-05fd-11ea-9682-3acbdd0a7c3d.png)

Like the picture said.
The Position: +/- 1mm Orientation: 0.1°.
But in actual use，I don’t think it can achieve such high accuracy.For example, virtual objects drift from time to time.
I used the HTC VIVE tracker to make a measurement, but the effect was not satisfactory.
can you  tell me what kind of measurement method is used to get that kind of data. I need to give Party A a document about accuracy.
Thank you。

**Comment by ckorris** [comment]
Those accuracy figures are from when the ZED/ZED Mini is in a suitable environment - well-lit, well-textured, feature-rich, and with a lack of moving or reflective objects. Rooms with lots of plain white walls, poor lighting, etc. will not support that level of accuracy. 

Even so, drift can still be expected because 1. very small errors can add up over time, and 2. individual frames may be difficult for the SDK (from someone moving, excessive motion blur, etc.). However, this is why we've created the Spatial Memory feature, so that if the ZED recognizes features it had seen before and notes a drift, it can correct itself. Have you had this feature enabled? 

Also feel free to share pictures of your environment and I can point out anything that looks like it might be a challenge for your tracking.
